### ISSUE TITLE
Remove the  codepen logo from the website 

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#1]
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/c88ab0af-658f-4345-a584-6c103241a44e)

**Comment by madhurafulkar** [comment]
Can you assign me this?

**Comment by Prajwal0225** [comment]
Ook, @madhurafulkar  you can start working on this issue 🙂
