### ISSUE TITLE
Enhance API Key Security

### ISSUE THREAD

**Issue by animeshchaudhri** [Prajwal0225/My-Favorite-SuperHero#101]
The current implementation exposes the Superhero API key  directly in the client-side JavaScript code. It's not recommended to expose your API keys in client-side code as it can be accessed by anyone. Consider moving it to a server-side environment or using environment variables.

## Impact

Exposing the API key presents a security risk for potential misuse of the key if discovered. It's a best practice to avoid embedding secrets in client-side code.

Moving the key to a server-side env var or secrets service will improve security and prevent leakage of the key.

**Comment by nitishkumar333** [comment]
Hi, please assign me this issue. I would like to work on it.

**Comment by madhurafulkar** [comment]
You can work on this issue @animeshchaudhri

**Comment by animeshchaudhri** [comment]
I have fixed the issue by proving a placeholder for it and added comments to JavaScript code for better readability.

**Comment by animeshchaudhri** [comment]
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/111721851/217cc63f-7a4a-4ebf-b52a-2aef34df1053)

**Comment by Prajwal0225** [comment]
Hey @animeshchaudhri 
I don't think we need a .env file to store our project's API key. Our API key is quite simple, and adding a .env file might make it harder for beginners to understand and work on the project.
