### ISSUE TITLE
Edit the Contributor's page.

### ISSUE THREAD

**Issue by arushitrivedi** [Prajwal0225/My-Favorite-SuperHero#117]
The page should display the cards of the owners of the project with their name and picture.

**Comment by arushitrivedi** [comment]
Please assign me this task to me.

**Comment by Prajwal0225** [comment]
Not just the owners but all the contributors that contributed to the website.

**Comment by madhurafulkar** [comment]
Please provide a general idea of what you would like to add to this page.
The page should display cards featuring the names and pictures of both project owners and all contributors who have contributed to the website.

Are you interested to work on this issue?
