### ISSUE TITLE
Redesign the UI of home screen 

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#120]
Try to change the UI of the home screen like this 

![WhatsApp Image 2023-10-05 at 8 59 32 AM](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/aa543ea8-bc9f-493f-bbfe-bc0a9f886196)

**Comment by Sebastianshrisunder** [comment]
I would like to update the home screen UI as mentioned above. Will make better changes
