### ISSUE TITLE
Show more than one image of the super hero

### ISSUE THREAD

**Issue by Piumir3** [Prajwal0225/My-Favorite-SuperHero#121]

**Comment by Pavilion-devs** [comment]
@Piumir3 please can you provide a screenshot ? @Prajwal0225 can you assign this to me?

**Comment by Pavilion-devs** [comment]
> @Piumir3 please can you provide a screenshot ? @Prajwal0225 can you assign this to me?

Just checked this @Prajwal0225 I noticed the superhero image works well but I think a screenshot and explanation will be nice @Piumir3 for more clarification

**Comment by madhurafulkar** [comment]
Please provide a general idea of what you would like to do @Piumir3

**Comment by clydehenry3** [comment]
@Prajwal0225 Is this issue still open to be assigned? I am assuming to throw some JS in here for images to populate.
