### ISSUE TITLE
Display contributors in repo on the Contributor nav list page

### ISSUE THREAD

**Issue by Pavilion-devs** [Prajwal0225/My-Favorite-SuperHero#123]
I noticed that whenever I click on the contributor link it shows an error. The main purpose of the page is to display the contributors working on this project. I can do this using github API. Can I be assigned to it @Prajwal0225 ?

![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/118903029/c7ad7777-506a-433a-abf1-10beb81db91f)

**Comment by Pavilion-devs** [comment]
@madhurafulkar @Prajwal0225 Kindly give me a response on this issue ?

**Comment by Prajwal0225** [comment]
This issue is already been resolved. Try to find other issues to work on.

**Comment by madhurafulkar** [comment]
Please provide a general idea of what you would like to add to this page.
The page should display cards featuring the names and pictures of both project owners and all contributors who have contributed to the website.

Are you interested to work on this issue?

**Comment by Pavilion-devs** [comment]
Yes I am @madhurafulkar

**Comment by madhurafulkar** [comment]
You can start working on this issue @Pavilion-devs

**Comment by Pavilion-devs** [comment]
@Prajwal0225 This issue is still being worked on by me and I see no reason it should be closed. I raised this issue earlier but you said there's no need for it and I tried explaining until your partner @madhurafulkar told me to go on with it. Remember this is not a Job it's just a contributed learning project.

**Comment by Prajwal0225** [comment]
Hi @Pavilion-devs 

Thank you for your dedication to this project and your commitment to resolving the issue in question. We appreciate your contributions.

It's clear that there might have been some confusion about the status of this issue earlier on. I apologize for the misunderstanding regarding its necessity. Your willingness to continue working on it is valuable to us, and we encourage your active participation.

**Comment by Pavilion-devs** [comment]
No problem. I'm currently on it

**Comment by Pavilion-devs** [comment]
@Prajwal0225 This issue is being resolved but there was a big change in the project which includes:
* I added a backend server on the project because for me to get contributors data I need to use github token and I can't expose mine since it's open source. So the project will continue to run on local host.
* I will also have to edit the READ.Me file to tell contributors on how to start the server using localhost

If you agree with this let me know so I can add this changes @Prajwal0225 @madhurafulkar 
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/118903029/62b3bbea-9813-4e77-91d0-4c584a9dbbb6)
