### ISSUE TITLE
Better UI needed for Superhero information

### ISSUE THREAD

**Issue by MurtazaShikari** [Prajwal0225/My-Favorite-SuperHero#134]
Can I create a visually more appealing UI for the superhero information page, the information currently appears like this as shown below in the screenshot?

![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/114511800/08165ae8-1065-4f04-a467-89b514bd94d3)

**Comment by madhurafulkar** [comment]
We need to fetch hero's information using an API and display the dynamically searched information as well.
Use this API - https://www.superheroapi.com/

Are you interested to work on it?

**Comment by MurtazaShikari** [comment]
Yes I would like to work on this @madhurafulkar

**Comment by madhurafulkar** [comment]
Could you please provide an update on the current status of the assigned task?
@MurtazaShikari

**Comment by madhurafulkar** [comment]
We are unassigning this issue as we've been waiting for your pull request, but it appears you're not interested in completing the work. @MurtazaShikari
