### ISSUE TITLE
Navbar in dark mode

### ISSUE THREAD

**Issue by madhurafulkar** [Prajwal0225/My-Favorite-SuperHero#138]
We're looking for someone interested in implementing a dark mode for our website's navbar.

Anyone interested?

**Comment by anshu-ee-21** [comment]
Yes I am interested.

**Comment by madhurafulkar** [comment]
Go ahead @anshu-ee-21

**Comment by Prajwal0225** [comment]
@anshu-ee-21 
Could you please provide an update on the current status of the assigned task?

**Comment by anshu-ee-21** [comment]
Yes @Prajwal0225, I have worked upon it. Do I raise a PR?


![navbar](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/98543901/2fb5f349-9b93-4b7f-acbe-504ad2cad990)

**Comment by Prajwal0225** [comment]
Raise a PR

**Comment by anushkapal28** [comment]
Hello! I'm interested in working on this task. I have experience with web development , and I'm eager to contribute. Please consider assigning this to me, and I'll get started right away. Thanks! I will make a worthful contribution.
