### ISSUE TITLE
Design a logo for website

### ISSUE THREAD

**Issue by madhurafulkar** [Prajwal0225/My-Favorite-SuperHero#139]
We are seeking a designer to create a logo for our website.

Anyone interested?

**Comment by Kallind** [comment]
hey, i know some designing i can try it using canva andd other resources

**Comment by madhurafulkar** [comment]
Yeah, you can try.  @Kallind 
Share the photos of what u had done

**Comment by Kallind** [comment]
hey i did make a logo but its not good i feel it can be done better ill try if i can

**Comment by Prajwal0225** [comment]
Could you please provide an update on your progress regarding the logo design, @Kallind?
