### ISSUE TITLE
Improve styling of the footer.

### ISSUE THREAD

**Issue by sakshin021** [Prajwal0225/My-Favorite-SuperHero#140]

**Comment by madhurafulkar** [comment]
Go ahead @sakshin021

**Comment by anushkapal28** [comment]
Hello! I'm interested in working on this task. I have experience with web development , and I'm eager to contribute. Please consider assigning this to me, and I'll get started right away. Thanks! I will make a worthful contribution.

**Comment by anushkapal28** [comment]
Hello! I'm interested in working on this task. I have experience with web development , and I'm eager to contribute. Please consider assigning this to me, and I'll get started right away. Thanks! I will make a worthful contribution.
