### ISSUE TITLE
Change the color of the 'Random Hero' button on hover

### ISSUE THREAD

**Issue by harshd008** [Prajwal0225/My-Favorite-SuperHero#144]

**Comment by Fer-Win** [comment]
Hey @Prajwal0225  Can I work on this issue?

**Comment by Sebastianshrisunder** [comment]
Hey can I edit this feature?

**Comment by ZainabR11** [comment]
@Prajwal0225 Can I work on this issue for Hacktoberfest? I have previously work on hover effect . Kindly assign this to me.

**Comment by PraffulPatel27** [comment]
Hey @Prajwal0225 ,
I'm eager to contribute to this issue I would like to change the color of the button.  and would appreciate it if you could assign me to work on it. I'm committed to delivering quality results and will provide a screenshot and a short video.

Button 
![buttons](https://github.com/divyanshudhruv/Minifolio/assets/110104505/53cf46ef-9c13-4122-956e-d1c772baf2cd)

When hover, the colour red
![hover red](https://github.com/divyanshudhruv/Minifolio/assets/110104505/07fb3fcc-a5a5-4494-a9f9-ad1c7f8c7a20)

When hover it colour red with red shadow effect 
![hover red with shadow effect](https://github.com/divyanshudhruv/Minifolio/assets/110104505/a265b6e2-2aa3-4f99-8af8-da50bbe35bc9)

Video of hover button

https://github.com/divyanshudhruv/Minifolio/assets/110104505/8c710614-9e31-48d7-a79b-1d8a8b7e4680

Thank you!
