### ISSUE TITLE
Adding a How to contribute section and Footer  in about page 

### ISSUE THREAD

**Issue by Pro-18** [Prajwal0225/My-Favorite-SuperHero#155]
I would like to enhance the About Page by including a dedicated section on how individuals can contribute to this project. This addition will provide clear guidance to potential contributors, fostering a more inclusive and collaborative environment.
Footer include a mentor information.

**Comment by madhurafulkar** [comment]
Go ahead @Pro-18

**Comment by GeeekySouro003** [comment]
Hello sir i will be very grateful if i get the oppurtunity to work on this.Please assign me on this.
