### ISSUE TITLE
[Fix]: The Buttons are going out of the outer box on the homepage

### ISSUE THREAD

**Issue by ishikagoyal02** [Prajwal0225/My-Favorite-SuperHero#158]
The Random Hero Button and Download Button are not fixed in the box on the Homepage.

![Uploading Screenshot 2023-10-12 000535.jpg…]()

**Comment by priyanshu-gupta0503** [comment]
hey@Prajwal0225  kindly assign this task to me and it is my request to add a hacktober fest label

**Comment by Prajwal0225** [comment]
You can start working on this issue @ishikagoyal02

**Comment by priyanshu-gupta0503** [comment]
thank you
