### ISSUE TITLE
comment-on-issue.yml is not generating comment after issue get generated 

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#16]
comment-on-issue.yml is located at .github/workflows

**Comment by akhilender-bongirwar** [comment]
@Prajwal0225,  I want to try this. Could you please assign me : ).

**Comment by akhilender-bongirwar** [comment]
I have seen the code and the error is in this part ` github.issues.createComment({ issue_number: github.context.issue.number, owner: github.context.repo.owner, repo: github.context.repo.repo, body: issueComment });`

**Comment by Prajwal0225** [comment]
Ok, you can work on this issue.
