### ISSUE TITLE
Display information of the heros

### ISSUE THREAD

**Issue by ishikagoyal02** [Prajwal0225/My-Favorite-SuperHero#164]
The website only displays the image on searching for the hero or clicking on the random button. It does not display any information regarding that hero.
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/99865224/57801a2e-8cca-40cc-a892-e601f50a16c7)
These elements remain constant.

Please assign me this issue.

**Comment by madhurafulkar** [comment]
We need to fetch hero's information using an API and display the dynamically searched information as well.
Use this API - https://www.superheroapi.com/

You can start working on it. This is high priority issue, so prioritize completing it.
