### ISSUE TITLE
Resize the background image

### ISSUE THREAD

**Issue by madhurafulkar** [Prajwal0225/My-Favorite-SuperHero#172]
Resize the background image (bg.jpg) to match the dimensions of the generated superhero image while ensuring that the button positions remain unchanged.

Anyone interested to work on it?

**Comment by Pinaka-Pani-18** [comment]
I am interested to work on this issue.
Can you share a screenshot or video of issue so that I can get much clarity about the issue?

**Comment by Prajwal0225** [comment]
https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/614d7195-b470-4d70-a49e-8950e94b38e1
