### ISSUE TITLE
The NavBar hover effect is not consistent for all the 3 pages .

### ISSUE THREAD

**Issue by 092vk** [Prajwal0225/My-Favorite-SuperHero#175]
All the 3 pages have different hover styles for nav bar , all the 3 pages should have a consistent hover effect , the hover effect applied on nav bar of home page looks best and must be applied to other 2 pages . 

[NavBarHoverEffect.webm](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/123629919/ded77877-92cb-47e2-bf4f-b16a524245d7)

**Comment by Shreshth-Srivastava** [comment]
Hello there, I have solved this issue so may I create a pull request for this ?

**Comment by MrDBC** [comment]
@Shreshth-Srivastava 
yes do so and refer this issue #175 on ur PR

**Comment by Shreshth-Srivastava** [comment]
Hello there, please assign this issue to me.

**Comment by Prajwal0225** [comment]
@092vk  
Could you kindly submit a pull request today? Otherwise, we may need to assign this issue to another contributor. Thank you!

**Comment by 092vk** [comment]
@Prajwal0225 solved
