### ISSUE TITLE
Title for about and contributors should be changed to show the brand tag

### ISSUE THREAD

**Issue by 092vk** [Prajwal0225/My-Favorite-SuperHero#176]
Currently the title of about page is set to about and for contributors page is set to contributors , this does not reflect the brand Superheroes , it should be changed to Superheroes/about for about page , to Superheroes/contributors for the contributors page . 

Here is a video with the problem solved . 
can you assign me this issue .

[Title.webm](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/123629919/f681b5a8-1f27-477e-aa1c-e0d177914726)

**Comment by therefat** [comment]
assign me

**Comment by 22Yash** [comment]
@Prajwal0225 can you asssign me?

**Comment by Prajwal0225** [comment]
@092vk 
Could you kindly submit a pull request today? Otherwise, we may need to assign this issue to another contributor. Thank you!

**Comment by 22Yash** [comment]
@Prajwal0225 can you Pls check  my pull request
