### ISSUE TITLE
Transfer the Information regarding Hactoberfest from about page to hacktoberfest page , also populate the about page. 

### ISSUE THREAD

**Issue by 092vk** [Prajwal0225/My-Favorite-SuperHero#177]
Currently the information regarding the hacktoberfest lies in the about page which should lie in the contributors page instead , the about page should be populated with information like 1.More info about the project , 2. TechStack used in making the project , 3. about the api from where we are fetching the superheroes images and information . 3. other information which is relevant to the project.

while the contributors page should include the steps to clone and setup the project , rules for making pull request etc 

can you assign me this issue , thanks .

**Comment by Prajwal0225** [comment]
You can start working on this issue @092vk

**Comment by aatiw** [comment]
can you please assign me this issue
