### ISSUE TITLE
An error occurred while fetching data.

### ISSUE THREAD

**Issue by madhurafulkar** [Prajwal0225/My-Favorite-SuperHero#184]
An error occurred while fetching data, preventing the generation of a hero image when searching, but it works when generated randomly.

Anyone interested to work on this?

**Comment by madhurafulkar** [comment]
![Screenshot 2023-10-15 093006](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/120560129/e5f47016-b0e2-4ebb-96bf-a9d8b9380fdd)

**Comment by asheshmandal2003** [comment]
Can I work on this?

**Comment by madhurafulkar** [comment]
You can start working on it @asheshmandal2003
