### ISSUE TITLE
Backup font

### ISSUE THREAD

**Issue by divyansh14kr** [Prajwal0225/My-Favorite-SuperHero#19]
Current css only has one font, include a generic font family as a fallback in case the custom font fails to load

**Comment by NereidaRondon** [comment]
Hello👋🏼 , I'd like to work on this issue. Thanks in advance.

**Comment by Chiro2002** [comment]
Hey, I'd like to contribute to this project too. Could you please assign me? I have previous experience working on web development with HTML, CSS, JS, and Django, so I think I can work well with you.
