### ISSUE TITLE
Superhero Name Not Displaying When Clicking on Random Hero Button

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#193]
When I click on the "Random Hero" button, the superhero name is not displaying as expected. Instead, it appears that there is an issue with the Superhero Name display functionality. This issue is particularly noticeable when compared to the normal search, where the Superhero name displays correctly.

After clicking the Random Hero button 
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/22e90403-a510-4709-8240-fe61575645e5)

But when we search superhero by its name by typing in the search bar name it shows properly 
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/e12a4165-19d7-4621-853d-441f21937c66)

**Comment by divyansh-4** [comment]
Hi, I think I can fix this issue. Kindly assign it to me.

**Comment by PrathameshTheurkar** [comment]
Hi @Prajwal0225 , can u assign this issue to me , I would like to contribute to this issue and can fix this issue.

**Comment by PrathameshTheurkar** [comment]
Solved the issue , plz review my PR #194

**Comment by madhurafulkar** [comment]
Go ahead @divyansh-4
