### ISSUE TITLE
Download superhero image with one click to your local computer. 

### ISSUE THREAD

**Issue by Pavilion-devs** [Prajwal0225/My-Favorite-SuperHero#200]
Download button doesn't work. It just shows a preview of the image on the site and that's all. I want to make it downloaded with one click into your local computer. Assign me to this issue bro @Prajwal0225

**Comment by Pavilion-devs** [comment]
Hey @Prajwal0225 @madhurafulkar I can't take on any issue anymore due to bad laptop. I wish you the best in this project and appreciate the time I spent here.

**Comment by Prajwal0225** [comment]
You did truly amazing work in this repository, and I sincerely appreciate it! 🙂

**Comment by love-sonkar** [comment]
hey @Prajwal0225  Can i work on this issue

**Comment by auth-02** [comment]
@Prajwal0225 @madhurafulkar can you entrust me with this issue?
