### ISSUE TITLE
After clicking on the search button the search box becomes empty for better user experience.

### ISSUE THREAD

**Issue by Sahil-K123** [Prajwal0225/My-Favorite-SuperHero#210]
On searching the SuperHero after clicking the search button the text in the search box should becomes empty which is good for **User Experience**.

### Current Status:

https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/123640518/d6ec62bb-7b90-4993-8135-eeedc0d16015

**Comment by Sahil-K123** [comment]
hii @Prajwal0225 , please assign this issue to me.

**Comment by DeepRahangdale** [comment]
@madhurafulkar  if the issue is still not solved i would love to work on thi assign me plz

**Comment by Prajwal0225** [comment]
@Sahil-K123  this issue is already resolved. Please try to find new issue to work on.
