### ISSUE TITLE
Improving the Styling The Curious Cases Part 

### ISSUE THREAD

**Issue by saurav2208** [Prajwal0225/My-Favorite-SuperHero#211]
The Curious Cases part looks very simple. It can be made more attractive and stylish.
![Screenshot (116)](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/125905089/837ca9b6-45f8-4e89-8815-55b862912149).

Please assign it to me under hacktoberfest 2023 label.

**Comment by saurav2208** [comment]
I have made a PR for this issue.

**Comment by saurav2208** [comment]
Hey, @Prajwal0225 I couldn't send a PR previously because of some issue that occurred in my Github account. So, I request you to kindly review the PR I have sent now.

**Comment by Prajwal0225** [comment]
When I click on one question all three question box get bigger and the answer is only shown to the click one

https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/531e0255-7802-40ed-ae3e-990803c34768

I think when the user clicks on the question the question box show pops up and shows the answer to whether other remaining questions remain the same.

**Comment by saurav2208** [comment]
@Prajwal0225 Okay doing the changes.
