### ISSUE TITLE
feature add: hero image will zoom on hover

### ISSUE THREAD

**Issue by Aksgo** [Prajwal0225/My-Favorite-SuperHero#213]
I would suggest to zoom in the image of the hero when hovering on it to have more clear view

**Comment by Aksgo** [comment]
this is what I am suggesting to do. I am just a beginner in open-source, this would be my first contribution. Please assign it to me.

**Comment by love-sonkar** [comment]
your idea is great just create a PR but don't over zoom images

**Comment by Aksgo** [comment]
Sir it would be helpful if you could assign it to me, so that it would count to my contribution

**Comment by hamzailyas237** [comment]
If this issue still persist. Assign it to me.
