### ISSUE TITLE
Download image as png or jpeg format on clicking download btn

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [Prajwal0225/My-Favorite-SuperHero#215]
On clicking on the download btn , The image should be downloaded as  png or jpeg kind of format , so that user can see his super hero image as of his interest :)

can you assign this to me , I am interested to contribute myself in hacktoberfest_23 : )

**Comment by Prajwal0225** [comment]
Hey @Bharath-KumarReddy, you can start working on this issue.
