### ISSUE TITLE
Issue: Text Alignment and Styling for Hacktober Box

### ISSUE THREAD

**Issue by chisfy** [Prajwal0225/My-Favorite-SuperHero#225]
![opensourceproject](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/137444313/5372bf6d-59c8-4c68-95fb-d495832df3d0)

Hi there, i'm looking to create my first contribution to an open source project, this is small and minor but i'm a beginner and i'd like to improve the text alignment into this box explaining what hacktober is.

I have no idea if this is already being worked on by someone else, apologies if it is.

**Comment by manisha765** [comment]
can you please assign me this issue , I would Like to work on this issue.

**Comment by chisfy** [comment]
Hi there, I have already made a pull request under this issue!
