### ISSUE TITLE
feat: search suggestions

### ISSUE THREAD

**Issue by abuemkezeChu** [Prajwal0225/My-Favorite-SuperHero#229]
The search bar should suggest names of superheroes as the user progressively types the name of the hero they are searching for.

**Comment by clydehenry3** [comment]
@Prajwal0225 @abuemkezeChu , please assign this to me. I also do UX design to make this relevant to user mental models.

**Comment by clydehenry3** [comment]
We can build what it looks like and can try to add JS for later after the structure has been made.
