### ISSUE TITLE
Improve Button Design and container width

### ISSUE THREAD

**Issue by akanshbende** [Prajwal0225/My-Favorite-SuperHero#24]
Hey Prajwal,

I hope you're doing well. I wanted to bring up an issue regarding the design of our buttons, the input search field, and the container width for certain elements, including the need for rounded corners on images.

The current button design may need improvement in terms of user experience and visual aesthetics. Additionally, the input search field is crucial, and we should ensure it is user-friendly. Please consider these aspects and any potential changes. I also suggest maximizing the container width for specific elements and adding rounded corners to images to enhance our overall interface. Your expertise is highly valuable, and I trust your judgment in making our product more user-friendly and visually appealing. Let's discuss this further in our upcoming design meeting. Thank you for your attention to these design concerns, Prajwal.

**Comment by harshu0001** [comment]
Please assign this issue to me. I'll make sure for the betterment of the appearance of the website as well. 
Thank you!

**Comment by Prajwal0225** [comment]
@akanshbende you can start working on the button design.

**Comment by akanshbende** [comment]
> @akanshbende you can start working on the button design.

Yes Done please review pull request

**Comment by akanshbende** [comment]
![Screenshot 2023-10-02 215505](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/76099756/f73fbc9e-3e4b-424f-975b-9965b4da781b)
Input bar,buttonand footer font has been changed.
![Screenshot 2023-10-02 215523](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/76099756/6e16ae04-9fac-4131-8d8a-2ff863536f96)

search bar text placed in middle,and style has been given to button,when hover will translate upward on right side.

![Screenshot 2023-10-02 215545](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/76099756/0b1bec7e-1351-4601-8730-f0051c6d573c)
image border radius changed and on hover on image will scale to 1.1 %
