### ISSUE TITLE
Enhance Superhero Image Size for Better Aesthetics

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#25]
**Description:**
The current display of the superhero image after searching appears smaller and does not provide an attractive user experience. To improve the visual appeal of our project, we need to increase the size of the displayed image.

**Image :**
![increase the image size ](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/7a6a7219-d7e4-44e5-b7f7-e9c842480443)

**Task Details:**
Increase the size of the displayed superhero image for better aesthetics.

**Comment by vamsi-spoidey7** [comment]
hey i would like to work on this issue as part of hacktober fest 2023. please assign me to this

**Comment by Prajwal0225** [comment]
This is a very simple task, So 
Can you make a pull request for this task by tomorrow?

**Comment by vamsi-spoidey7** [comment]
yeah for sure
