### ISSUE TITLE
Invalid Search Improvement

### ISSUE THREAD

**Issue by Tanya347** [Prajwal0225/My-Favorite-SuperHero#264]
On searching something invalid, we can still see the download button. I think it would be more comprehensive to not let the user search the wrong thing in the first place i.e. when they click on the search button there should be a small popup to alert the user that it is invalid, and clear the search input. Please let me work on this issue

![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/80675137/77a14f48-7cfd-4627-91f2-1f12589b25c8)

**Comment by Prajwal0225** [comment]
You can start working on this issue.

**Comment by Tanya347** [comment]
Since someone already added this feature before I could I'm just going to fix this :
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/80675137/3ff2d8b8-c706-4e44-acc6-6ce927048d42)

and make this area more readable:
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/80675137/23435698-dea2-43ac-9d5d-82d2da53bb11)
