### ISSUE TITLE
Create Navigation Bar with Home, About, and Contributors Sections

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#27]
**Description:**
We're looking to enhance the user experience of our website by implementing a navigation bar that will provide easy access to essential sections. This navigation bar should include sections like **_Home_**, **_About_**, and **_Contributors_**.

**Task Details:**

**Navigation** Bar Design: Develop a simple and user-friendly navigation bar that aligns with our website's style and layout.
**Home Section**: This is the link to our website's main page, which will remain unchanged.
**About Section**: Create a 'About' page with an H1 tag that says "Coming Soon".
**Contributors Section**: Similarly, generate a 'Contributors' page with an H1 tag indicating "Coming Soon." 
**Responsive Design**: Ensure the navigation bar functions well on all screen sizes and devices, maintaining a pleasing appearance and usability.

**We will add the Code to the About and Contributors page afterward.**

**Comment by Ir786921** [comment]
hey,can you please assign this task to me .

**Comment by Priyanshume18** [comment]
hey, i would love to make the nav bar for you.Please assign it to me

**Comment by Prajwal0225** [comment]
@Ir786921
Are you willing to commit to completing this task within the next 3 to 4 days at most?

**Comment by bhalerao-2002** [comment]
Hi @Prajwal0225, 
I have gone through the code and understand the API work is great, but for visitor retention and ease, we need a fully functional Navbar,
Please, Assign me this issue and I will raise my PR ASAP🚀.

**Comment by Priyanshume18** [comment]
i can do this within today only

**Comment by Baburao-sanivada** [comment]
Can i Work on This?

**Comment by VishnuAmit** [comment]
Hi @Prajwal0225 . I can create you a user-friendly and responsive navigation bar that exactly matches the theme of your website. 
I have done pretty good websites in the past and I'd like to contribute to your website. Looking forward !

**Comment by Ir786921** [comment]
yes ,@Prajwal0225  I 
love to complete this task within today only.

**Comment by kadamprashant1** [comment]
@Prajwal0225 can I add new styling in the search bar?
please assign me this issue...

**Comment by Pranavnk15** [comment]
I have fixed the issue, and have submiited the PR along with the snap of the changes made, have a look...

**Comment by rajanarahul93** [comment]
i want to work on this issue ,please assign this issue to me
