### ISSUE TITLE
Add some transition effect on hero img on hover

### ISSUE THREAD

**Issue by Monika-1082005** [Prajwal0225/My-Favorite-SuperHero#278]
**I want to add some transition when an user hovers on the hero image as now it is way too basic.**

_Here is the reference of how it is going to look like exactly._

https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/134940879/f2902e16-73de-42d2-93e4-4892120ac987

**Comment by suhas-sensei** [comment]
i'd be happy if im assigned this issue
