### ISSUE TITLE
 Logo Click Redirect Issue to GitHub Page Instead of Vercel Deployed Home Page

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#280]
Issue Description:

When clicking on the logo on our website, it currently redirects to the GitHub page, while it should redirect to the Vercel deployed home page. This inconsistency in behavior is causing confusion for our users and needs to be addressed.

https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/2026b9a2-7500-47f9-a6c9-971ec8840596

Please let me know if you need any additional information or assistance to resolve this issue.

**Comment by love-sonkar** [comment]
There is one more issue the styling is not applying when you click in logo

**Comment by Prajwal0225** [comment]
Hey @love-sonkar, you can start working on this issue.  Please try to do it as soon as possible.

**Comment by love-sonkar** [comment]
okay bro

**Comment by love-sonkar** [comment]
@Prajwal0225  check my PR
