### ISSUE TITLE
display hero information properly 

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#281]
Currently, hero information is displayed like this

![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/e30bfccc-e5ed-4e15-8a64-4d2a34e82aaa)
It's not looking good 

So change formate like this 
Change Aliases to Name

Name : Ethan Hunt  
Strength : 11
Speed: 29
Gender: Male
Place Of Birth : Mandison,United states of America 
First Appearance : -

**Comment by Vybhavigithub** [comment]
@Prajwal0225 Could you please assign me this issue?

**Comment by Prajwal0225** [comment]
Hey @Vybhavigithub, you can start working on this issue. If it's possible, please aim to create a pull request (PR) within the next 2 days.

**Comment by Vybhavigithub** [comment]
okay

**Comment by suhas-sensei** [comment]
hey @Prajwal0225 can you review the pr i made on this issue
