### ISSUE TITLE
Change the text 

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#282]
Change the text From
[Please Choice Your Heroes to Type Hero Name]

![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/2bfb405e-8cc0-44f2-b559-79a04420c7b4)

**Comment by saurav2208** [comment]
@Prajwal0225  Please assign me to work on this issue.

**Comment by Prajwal0225** [comment]
Hey @saurav2208 , you can start working on this issue. If it's possible, please aim to create a pull request (PR) within the next 2 days.

**Comment by saurav2208** [comment]
@Prajwal0225 Sure!
