### ISSUE TITLE
Add simple hover effect to random image and download button

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#283]
The hover effect on random images and the download button is not good. Apply a hover effect that suits our website style.

**Comment by ankitkumar0622** [comment]
Hi, can you please assign this task to me.

**Comment by Prajwal0225** [comment]
Hey @ankitkumar0622, you can start working on this issue.

**Comment by Yuvraj918** [comment]
i have an idea for this issue so assign me this issue

**Comment by Prajwal0225** [comment]
@Yuvraj918, are you interested in solving this issue?

**Comment by Shantanu-Tiwari** [comment]
Hey I would like to work on this issue.
