### ISSUE TITLE
Style search bar 

### ISSUE THREAD

**Issue by Prajwal0225** [Prajwal0225/My-Favorite-SuperHero#284]
Change the search bar design from this
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/0678cfb8-c9b4-400d-a470-004f13f372da)

Too, something like this ⤵️ 
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/103810119/4403a7ed-1752-46c9-a1f6-e66e210789b2)

**Comment by ankitkumar0622** [comment]
Hi, can you please give assign me this task.

**Comment by Prajwal0225** [comment]
Hey @ankitkumar0622, I already assigned you issue #283 please make a PR for it first.
Once you've completed the PR for issue #283, if this issue is still available, we'd be happy to assign it to you as well.

**Comment by bhavya-anand19** [comment]
@Prajwal0225 Please assign me this issue

**Comment by Prajwal0225** [comment]
Hey @bhavya-anand19 , you can start working on this issue. If it's possible, please aim to create a pull request (PR) within the next 2 days.

**Comment by bhavya-anand19** [comment]
@Prajwal0225 Okay. I will surely do it.

**Comment by Maedamori22** [comment]
can you assign me?

**Comment by Yuvraj918** [comment]
i want to work on this issue, so please assign me
