### ISSUE TITLE
Create a new search bar design for Home page.

### ISSUE THREAD

**Issue by kadamprashant1** [Prajwal0225/My-Favorite-SuperHero#32]
Can you assign me this issue

**Comment by Prajwal0225** [comment]
Okay, you can begin working on this issue. Please try to create a pull request by tomorrow.

**Comment by rajanarahul93** [comment]
i want to work on this issue ,please assign this issue to me

**Comment by Mohd786-hub** [comment]
please assign this to me so that i contribute to this hactoberfest 2023 . i have excellent knowledge of web dev and you can also check my projects in my repositories.
