### ISSUE TITLE
how can we contribute for hacktoberfest

### ISSUE THREAD

**Issue by shrey141102** [Prajwal0225/My-Favorite-SuperHero#35]
@Prajwal0225 what enhancements can we make

**Comment by aryanksanghvi** [comment]
I can improve the button style and hovering effects

**Comment by Prajwal0225** [comment]
You are welcome to suggest any additions or improvements to the website. If necessary, we can assign you the issue, and you can commence work on it.

**Comment by aryanksanghvi** [comment]
what work is left to be assigned?

**Comment by Prajwal0225** [comment]
background does not look good you can work on it. If you are interested.

**Comment by aryanksanghvi** [comment]
Yes ok!

**Comment by aryanksanghvi** [comment]
we can also add a transition that will zoom in the photo of the superhero on hover
please assign me this task

**Comment by aryanksanghvi** [comment]
we can also add a transition that will zoom in the photo of the superhero on hover
please assign me this task

**Comment by Prajwal0225** [comment]
Create a new issue related to background change. I will assign that issue to you.

**Comment by Prajwal0225** [comment]
Sorry, but issue #36 has already been raised try to find the new issue to work on.

**Comment by aryanksanghvi** [comment]
What else can you suggest me?
