### ISSUE TITLE
Website Needs a more lively background

### ISSUE THREAD

**Issue by Priyanshume18** [Prajwal0225/My-Favorite-SuperHero#36]
Although the background is soothing ,but it can be made much attractive if we add a fantastic background image with some transitions on hovering over.

**Comment by Priyanshume18** [comment]
Hey\, please assign me this task

**Comment by Priyanshume18** [comment]
Sir, please add it to hactoberfest too

**Comment by Prajwal0225** [comment]
Start working on it.

**Comment by Mohd786-hub** [comment]
please assign this to me so that i contribute to this hactoberfest 2023 . i have excellent knowledge of web dev and you can also check my projects in my repositories.
