### ISSUE TITLE
[Feature]: Display a quote related to the superhero to the user

### ISSUE THREAD

**Issue by Priyanshume18** [Prajwal0225/My-Favorite-SuperHero#37]
As of now only a photograph of the superhero is displayed ,but if we also display some quote based on the powers of the superhero it will make the users to connect in much better way.

Current website:
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/118612382/dbcfc151-fd46-4f0f-abc5-30bf36eca1cc)

then it will look something like this:
![Uploading image.png…]()

**Comment by Priyanshume18** [comment]
hey, please assign this task to me, i'll do within a day or two.

**Comment by Priyanshume18** [comment]
Sir, please add it to hactoberfest too

**Comment by Prajwal0225** [comment]
2nd image is not visible So I can't see what you are trying to do can you please send a proper photo so that I get a clear Idea about your thought?

**Comment by Priyanshume18** [comment]
https://www.bing.com/images/search?view=detailV2&ccid=H9a%2fxlVr&id=CD78FD6B999A7452AC86FD75F99EF2FBBF0F302A&thid=OIP.H9a_xlVrLf87a-G1uD5nFAHaFC&mediaurl=https%3a%2f%2fcdn.ilovefreesoftware.com%2fwp-content%2fuploads%2f2015%2f07%2fSuperhero-Name-Generator.jpg&exph=535&expw=787&q=html+css+superhero+websites&simid=608004968386215831&FORM=IRPRST&ck=C814352C0CBE630F2B4CDC12CAF4A064&selectedIndex=27&ajaxhist=0&ajaxserp=0

**Comment by Prajwal0225** [comment]
You Can Start working on this issue.

**Comment by Sairam-K26** [comment]
Can you assign it to me , it will be useful for my first pr for hactoberfest 2k23
