### ISSUE TITLE
Fix Inconsistent Footer Placement for Improved User Experience

### ISSUE THREAD

**Issue by premsaivarmachekuri** [Prajwal0225/My-Favorite-SuperHero#49]
# Description

The footer in our project is currently inconsistent. On the home page, it is not consistently at the bottom of the page, and when searching for superhero images, it is loaded in a way that causes the footer to shift down. This inconsistency affects the visual appeal and user experience of our project.

# Expected Behavior

The expected behavior is to have a consistent footer placement throughout the project. The footer should always be at the bottom of the page, regardless of whether users are on the home page or searching for superhero images. This will provide a more uniform and visually pleasing user experience.

# Screenshot
**Home Page**
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/110842297/92ff5ecf-5e1a-43fe-ac96-60e698ea004e)
**When Searching Favourite Hero**
![image](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/110842297/482bcbee-17a7-4538-a717-f5b6b6bc3089)

# Additional Context

Resolving this issue is essential for improving the overall visual appeal and user experience for our project's users. Inconsistencies in the footer placement can give the impression of an unpolished user interface. Ensuring that the footer remains consistently at the bottom of the page will contribute to a more professional and user-friendly design.

- [x] I have read the Contributing Guidelines.

**Comment by anshul-132002** [comment]
@premsaivarmachekuri Assign me to solve this problem

**Comment by Alekhya-Dharam** [comment]
can u pls assign this issue to me??
