### ISSUE TITLE
Adding About Page

### ISSUE THREAD

**Issue by Pro-18** [Prajwal0225/My-Favorite-SuperHero#51]
Adding About Page would be enhance the website experience
Assign me this task under Hacktoberfest
<img width="794" alt="about" src="https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/92087279/bc3261eb-d4c0-434f-96c6-00b5adf95e1e">

**Comment by Chiro2002** [comment]
Hey, I'd like to contribute to this project too. Could you please assign me? I have previous experience working on web development with HTML, CSS, JS, and Django, so I think I can work well with you.
