### ISSUE TITLE
Cleaning code using flexbox for styling and footer links

### ISSUE THREAD

**Issue by Pavilion-devs** [Prajwal0225/My-Favorite-SuperHero#56]
@Prajwal0225 I noticed that fixed width and height were mostly used and might cause issues when trying to make responsive. I suggest using flexbox to make it easier and the footer links load on the same tab when clicked on instead of directing to another tab. Mind if I take on this suggested issues @Prajwal0225

**Comment by Pavilion-devs** [comment]
Done. Created a PR!

**Comment by rajanarahul93** [comment]
i want to work on this issue ,please assign this issue to me
