### ISSUE TITLE
No display whenever you try to search for a superhero name

### ISSUE THREAD

**Issue by Pavilion-devs** [Prajwal0225/My-Favorite-SuperHero#59]
I tried searching for a wrong superhero name and nothing displayed. Mind if I take on this issue @Prajwal0225

**Comment by Prajwal0225** [comment]
What you are going to do to solve this issue?

**Comment by Pavilion-devs** [comment]
I'm getting an error "TypeError: Cannot read properties of undefined (reading '0')
    at script.js:23:32" which means the result array is empty when the superhero cannot be found. So to clear the error we will have to check if the results error exists and if it contains any elements before accessing the first element (json.results[0]). @Prajwal0225

**Comment by Pavilion-devs** [comment]
@Prajwal0225 I have fixed this issue already. Should I create a PR ?

**Comment by Prajwal0225** [comment]
Can you do something like If the user enters an incorrect superhero name, it will display the message, 'A superhero with this name does not exist on the website.

**Comment by Pavilion-devs** [comment]
Yes @Prajwal0225 . I already did that but I need your permission to push and make a PR ?

**Comment by Prajwal0225** [comment]
Please make a Pr my cloning updated code from the repo.

**Comment by Mohd786-hub** [comment]
please assign this to me so that i contribute to this hactoberfest 2023 . i have excellent knowledge of web dev and you can also check my projects in my repositories.

**Comment by Pavilion-devs** [comment]
Already done  @Prajwal0225  @Mohd786-hub. Just made a PR on it. You can check other issues.

**Comment by himanshu181749** [comment]
@Prajwal0225  i've  raised a PR please have a look...
