### ISSUE TITLE
Add a customized scrollbar 

### ISSUE THREAD

**Issue by akhilender-bongirwar** [Prajwal0225/My-Favorite-SuperHero#60]
- To improve the website's design I would like to add a customized scrollbar.
- This will enhance the user experience.

**Comment by akhilender-bongirwar** [comment]
@Prajwal0225, I would like to work on this issue.

**Comment by Prajwal0225** [comment]
Please elaborate on what you are going to do. I didn't understand the issue

**Comment by akhilender-bongirwar** [comment]
Sure @Prajwal0225. I have attached the below ss for the change I want to implement.
![Screenshot 2023-10-02 215729](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/112749383/b5dbf656-d600-4158-bb32-71bbfb423486)

I have customized the scrollbar for better user experience

**Comment by Prajwal0225** [comment]
Ok, You can start working on this issue
