### ISSUE TITLE
Fix Random Hero Button and Download button size 

### ISSUE THREAD

**Issue by harshhgithub** [Prajwal0225/My-Favorite-SuperHero#67]
![Screenshot (143)](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/133668600/8f5693f9-4123-471c-8c30-afc49059c333)

Please assign me this issue .

Also add the hacktoberfest and hacktoberfest-accepted label

**Comment by Prajwal0225** [comment]
Ok, you can work on this issue.

**Comment by harshhgithub** [comment]
#68 Done 
Please add the hacktoberfest and hacktoberfest-accepted label there .
Thanks
