### ISSUE TITLE
CSS code has been repeated in style.css file 

### ISSUE THREAD

**Issue by akanshbende** [Prajwal0225/My-Favorite-SuperHero#73]
CSS code has been repeated in style.css file  this might collide in future

**Comment by Mohd786-hub** [comment]
please assign this to me so that i contribute to this hactoberfest 2023 . i have excellent knowledge of web dev and you can also check my projects in my repositories.

**Comment by anshul-132002** [comment]
@akanshbende Assign me to solve this problem
