### ISSUE TITLE
Improve the navigation bar

### ISSUE THREAD

**Issue by pushkar1713** [Prajwal0225/My-Favorite-SuperHero#75]
I want to work on the naviagtion bar and try to improve/implement the following changes
- Change the background color
- Change the font and also add change color property on hover
- Centre the 3 elements (home, about, contributors).

**Comment by Sumitwarrior7** [comment]
assign it to me, i ll love to work for it

**Comment by Mohd786-hub** [comment]
please assign this to me so that i contribute to this hactoberfest 2023 . i have excellent knowledge of web dev and you can also check my projects in my repositories.

**Comment by mohit5723** [comment]
please assign this to me so that i contribute to this hactoberfest 2023. I have read the improvements and specifications and can provide solution to it

**Comment by anshul-132002** [comment]
@pushkar1713 Assign me to solve this problem
