### ISSUE TITLE
update navbar

### ISSUE THREAD

**Issue by AnishHazra** [Prajwal0225/My-Favorite-SuperHero#78]
can you assigned to me i can fix and improve the navbar

**Comment by Chiro2002** [comment]
Hey, I also want to contribute to this. Can you assign me to this project, please ?

**Comment by madhurafulkar** [comment]
Already assigned this issue. Try to find new issue.

**Comment by Chiro2002** [comment]
Anything work for hactoberfest becoz I am beginner to this and want to contribute!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
