### ISSUE TITLE
new footer design

### ISSUE THREAD

**Issue by kadamprashant1** [Prajwal0225/My-Favorite-SuperHero#79]
I can solve this issue. Can you sign me?

**Comment by Chiro2002** [comment]
Hey, I'd like to contribute to this project too. Could you please assign me? I have previous experience working on web development with HTML, CSS, JS, and Django, so I think I can work well with you.

**Comment by ujjwalshivhare** [comment]
Hello mam,
can you please assign me this issue

**Comment by GeeekySouro003** [comment]
Hello sir i will be very grateful if i get the oppurtunity to work on this.Please assign me on this.
