### ISSUE TITLE
Improving fonts in your website

### ISSUE THREAD

**Issue by Sumitwarrior7** [Prajwal0225/My-Favorite-SuperHero#81]

**Comment by madhurafulkar** [comment]
You can begin working on this issue.

**Comment by ujjwalshivhare** [comment]
hello mam ,
can you assign me this issue

**Comment by rajanarahul93** [comment]
"Please assign the font improvement task to me."

**Comment by anushkapal28** [comment]
Hello! I'm interested in working on this task. I have experience with web development , and I'm eager to contribute. Please consider assigning this to me, and I'll get started right away. Thanks! I will make a worthful contribution.

**Comment by Sumitwarrior7** [comment]
@madhurafulkar assign this issue to @anushkapal28
