### ISSUE TITLE
The links in header are not working.

### ISSUE THREAD

**Issue by PiyushK79** [Prajwal0225/My-Favorite-SuperHero#85]
1 issue - Even though the UI looks good but the links in the header are not working, it goes to a 404 error page.

2 issue - I searched Spiderman, but it didn't fetched the images of him. So it may be that the api used doesn't contain the images of some superheros.

3 issue- The hover button of the search button is grayish and not going with the website.

4  issue-  As soon as the user enter the name of the superhero and press the enter button the website does not search the hero until the search button is clicked. I would like to add the enter key search functionality to the search.

Please assign this issues to me under HacktoberFest 2023 so that I can start working on it.

**Comment by madhurafulkar** [comment]
You can start working on these issues @PiyushK79

**Comment by Prajwal0225** [comment]
Issue 1 - navbar is now properly liked with about and contributors page.

**Comment by Prajwal0225** [comment]
Issue 1 - The navbar is now properly liked with the About and Contributors page.

You can work on issues 2,3 and 4.

**Comment by PiyushK79** [comment]
Alright!!
