### ISSUE TITLE
[bug]: UI will break when superhero is not found

### ISSUE THREAD

**Issue by manipandit** [Prajwal0225/My-Favorite-SuperHero#89]
When there is no result from API, the background gets distorted.

![layout-fix](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/110151059/1c6c07c2-9b0c-414f-afd3-30582a696c4d)

Assign me this, I would like to contribute.

**Comment by ymohit1603** [comment]
Hey can you assign this issue to me I wanna work on it.

**Comment by madhurafulkar** [comment]
You can work on this issue @manipandit
