### ISSUE TITLE
Folk dances

### ISSUE THREAD

**Issue by Swastik200** [Prajwal0225/My-Favorite-SuperHero#9]
Creating an Indian map clicking on each state will direct us to folk dances using html and css

**Comment by Prajwal0225** [comment]
I didn't understand anything can you explain this in detail?

**Comment by Swastik200** [comment]
Basically will create a indian map with all the states on it using maparea
linking on any state will show its folk dances directly

**Comment by Prajwal0225** [comment]
How do you plan to implement it on the website?

**Comment by Swastik200** [comment]
Just adding an unique feature

**Comment by Prajwal0225** [comment]
Could you please provide further details? I didn't fully grasp your suggestion regarding our project, which involves a simple superhero image search. Specifically, you mentioned adding an Indian map to it. I would appreciate it if you could elaborate on this idea.

**Comment by Swastik200** [comment]
Sure, no problem. ....I will create an Indian map with states on it
clicking on which show the folk dances associated with using html and css
maparea

**Comment by Prajwal0225** [comment]
But, I don't think it will align with our project. Therefore, I kindly request that we explore alternative issues to work on.
