### ISSUE TITLE
Navigation Button UI and other UI changes

### ISSUE THREAD

**Issue by yuvyy** [Prajwal0225/My-Favorite-SuperHero#90]
The search button is not aligned properly with the search bar. The download button can be better placed under the image to create an even look. The hover color of the "Random Hero" button can be changed to a one which is more relevant to the current UI.

**Comment by yuvyy** [comment]
I would like to be assigned this issue

**Comment by madhurafulkar** [comment]
You can work on this issue @yuvyy
