### ISSUE TITLE
Search Bar UI

### ISSUE THREAD

**Issue by ymohit1603** [Prajwal0225/My-Favorite-SuperHero#94]
Hey i would suggest that when user focus on the search bar the text would clear up
It would be more user friendly.

![Screenshot (51)](https://github.com/Prajwal0225/My-Favorite-SuperHero/assets/114051505/341ad93c-4790-41ef-af06-a92ea9249519)

**Comment by madhurafulkar** [comment]
You can work on this issue @ymohit1603

**Comment by ymohit1603** [comment]
@madhurafulkar hey i just made a pr have a look at that
